TARGETS = \TARGETS = \
	MorseConverter

MorseConverter: 
	g++ -o main ./Source/main.cpp ./Source/BinaryConverter/BinaryConverter.cpp ./Source/CodeConverter/CodeConverter.cpp ./Source/HangulParser/HangulParser.cpp ./Source/MorseConverter/MorseConverter.cpp ./Source/jsoncpp/jsoncpp.cpp